# SPDX-FileCopyrightText: 2026 Lucas Saavedra Vaz
# SPDX-License-Identifier: Apache-2.0

"""Protocol and layout reference values for integration tests and CI."""

from __future__ import annotations

from esp32_mock_bootloader import chips

ESPTOOL_CHIPS = list(chips.SUPPORTED)

TRANSPORTS = ['tcp', 'pty']

SYNC_PAYLOAD = bytes([0x07, 0x07, 0x12, 0x20]) + (b'\x55' * 32)
SYNC_RESPONSE_COUNT = 8

SLIP_RESPONSE_DIRECTION = 0x01

FLASH_APP_OFFSET = 0x10000

STUB_IRAM_ENTRY = 0x40080000
STUB_UPLOAD_BLOCK = 0x100

OHAI_BYTES = bytes([0x4F, 0x48, 0x41, 0x49])

STAY_IN_LOADER = 1
RUN_ENTRYPOINT = 0

FLASH_ERASE_BYTE = 0xFF
DIFF_FLASH_SECTOR_COUNT = 4

SPI_CMD_READ_ID = 0x9F
SPI_CMD_RDSFDP = 0x5A

ESP32_SPI_REG_BASE = 0x3FF42000
ESP32_SPI_USR2_OFFS = 0x24
ESP32_SPI_W0_OFFS = 0x80

ESP32C3_SPI_REG_BASE = 0x60002000
ESP32C3_SPI_W0_OFFS = 0x58

UNKNOWN_COMMAND = 0xFE

__all__ = [
    'DIFF_FLASH_SECTOR_COUNT',
    'ESPTOOL_CHIPS',
    'ESP32C3_SPI_REG_BASE',
    'ESP32C3_SPI_W0_OFFS',
    'ESP32_SPI_REG_BASE',
    'ESP32_SPI_USR2_OFFS',
    'ESP32_SPI_W0_OFFS',
    'FLASH_APP_OFFSET',
    'FLASH_ERASE_BYTE',
    'OHAI_BYTES',
    'RUN_ENTRYPOINT',
    'SLIP_RESPONSE_DIRECTION',
    'SPI_CMD_RDSFDP',
    'SPI_CMD_READ_ID',
    'STAY_IN_LOADER',
    'STUB_IRAM_ENTRY',
    'STUB_UPLOAD_BLOCK',
    'SYNC_PAYLOAD',
    'SYNC_RESPONSE_COUNT',
    'TRANSPORTS',
    'UNKNOWN_COMMAND',
]
